and back to normal

diff --git a/.azure-pipelines/unix-build.yml b/.azure-pipelines/unix-build.yml
--- a/.azure-pipelines/unix-build.yml
+++ b/.azure-pipelines/unix-build.yml
@@ -12,9 +12,9 @@ steps:
 
 - task: Cache@2
   inputs:
-    key: '"repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)-B" | installer/bootstrap.py | "$(TODAY_ISO)"'
+    key: '"repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py | "$(TODAY_ISO)"'
     restoreKeys: |
-      "repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)-B" | installer/bootstrap.py
+      "repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py
     path: $(Pipeline.Workspace)/modules
     cacheHitVar: REPOSITORIES_CACHED
   displayName: Restore repository cache
@@ -110,13 +110,12 @@ steps:
     export DIALS_DATA=$(pwd)/data
     . build/setpaths.sh
     cd modules/dials
-    libtbx.pytest -ra test/test_scitbx.py || echo "##vso[task.complete result=Failed;]Some tests failed"
+    libtbx.pytest -ra -n auto --runslow --regression || echo "##vso[task.complete result=Failed;]Some tests failed"
   displayName: Run tests
   workingDirectory: $(Pipeline.Workspace)
 
 - script: |
     echo Preparing cache
-    du -sh modules
     for repository in modules/*; do
       if [ -e ${repository}/.git ]; then
         echo Cleaning directory ${repository}
@@ -128,7 +127,6 @@ steps:
       fi
     done
     ls -la modules
-    du -sh modules
   displayName: Preparing cache
   workingDirectory: $(Pipeline.Workspace)
   condition: ne(variables.REPOSITORIES_CACHED, 'true')
