catch the exitcode

diff --git a/.azure-pipelines/windows-build.yml b/.azure-pipelines/windows-build.yml
--- a/.azure-pipelines/windows-build.yml
+++ b/.azure-pipelines/windows-build.yml
@@ -185,9 +185,8 @@ steps:
     rem export DIALS_DATA=$(pwd)/data
     call dials.bat
     cd modules/dials
-    echo pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 \
-        --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
-    pytest -v -ra --timeout=5400
+    echo pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
+    pytest -v -ra --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
   displayName: Run some tests (temporary)
   workingDirectory: $(Pipeline.Workspace)
 
